### ISSUE TITLE
Not working with mixed active content in firefox

### ISSUE THREAD

**Issue by s1-ranjan** [justoverclockl/geo-weather#1]
Firefox blocks the mixed active contents in Firefox, please have a look at the following image
![Screenshot from 2021-08-10 00-00-03](https://user-images.githubusercontent.com/20767253/128756652-6fe76868-8005-4cbc-86c9-b49b42d23f2d.png)

**Comment by justoverclockl** [comment]
The best strategy to avoid mixed content blocking is to serve all the content as HTTPS instead of HTTP

**Comment by justoverclockl** [comment]
I will fix this asap

**Comment by justoverclockl** [comment]
Can you try now with last update?
should be fixed

**Comment by s1-ranjan** [comment]
no its not working

**Comment by s1-ranjan** [comment]
By changing http://api.openweathermap.org/data/2.5/onecall?lat="+t+"&lon="+o+"&lang="+(r.a.forum.attribute("lang")||"en")+"&appid= to https://api.openweathermap.org/data/2.5/onecall?lat="+t+"&lon="+o+"&lang="+(r.a.forum.attribute("lang")||"en")+"&appid= in forum.js file located in /var/www/flarum/vendor/justoverclock/geo-weather/js/dist fixed my issue

**Comment by justoverclockl** [comment]
i've make these changes into last version :) so if you update the extension and clear cache, the issue is fixed :)

reference: https://github.com/justoverclockl/geo-weather/blob/main/js/src/forum/GeoWeather.js#L28

**Comment by justoverclockl** [comment]
be sure that u are running on 0.1.7 version
