### ISSUE TITLE
I don't know why, he didn't show me the weather here

### ISSUE THREAD

**Issue by vlssu** [justoverclockl/geo-weather#2]
I don't know why, he didn't show me the weather here, I am in China.
![image](https://user-images.githubusercontent.com/43847794/133892340-bc56b463-950f-4298-8638-89bef611ad0f.png)

**Comment by justoverclockl** [comment]
Did you put the api key into extension settings?
If yes pls
Check the console error please, maybe you’ve reached the limit?

**Comment by vlssu** [comment]
He couldn't use it yesterday, but he suddenly recovered today.
And the API that I applied for yesterday does not have a limit on the number of times, but it may be caused by other reasons.
