### ISSUE TITLE
API call command

### ISSUE THREAD

**Issue by efast1568** [justoverclockl/geo-weather#4]
https://api.openweathermap.org/data/2.5/onecall?lat=${lat}&lon=${long}&lang=${lang}&appid=${API_KEY}

Is it possible to use "weather" command instead of "onecall"? It appears to be the same as the previous FREE usage policy. There is no such strict limit on the number of calls. 

When my onecall reaches the upper limit, I can still use the "weather"  command to get a response

https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${long}&lang=${lang}&appid=${API_KEY}

**Comment by justoverclockl** [comment]
maybe because the weather have another limits, but i think weather is limited the same way.
